ChangeLog update APX checking fixed - wrong file in m4 (ax_with_apxs.m4) APACHE 2.0.x version check by presence of ap_release.h
git-svn-id: file:///data/svn/enum/mod_eppd/trunk@4935 b60c293d-5e0d-0410-87b2-fb9704ccd4b5

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -975,7 +975,8 @@ CXXFLAGS
 CCC
 CXXCPP
 F77
-FFLAGS'
+FFLAGS
+APXS'
 
 
 # Initialize some variables set by options.
@@ -1588,7 +1589,7 @@ Optional Packages:
   --with-xml-exec-prefix=PFX Exec prefix where libxml is installed (optional)
   --with-orbit-prefix=PFX   Prefix where ORBIT is installed (optional)
   --with-orbit-exec-prefix=PFX Exec prefix where ORBIT is installed (optional)
-  --with-apxs=PATH        Path to apxs
+  --with-apxs=APXS        absolute path name of apxs executable
   --with-apr-config       location of apr-config executable
   --with-idldir           Directory with idl [/usr/share/idl/fred/]
   --with-idl              location of idl file containing EPP interface
@@ -1612,6 +1613,7 @@ Some influential environment variables:
   CXXCPP      C++ preprocessor
   F77         Fortran 77 compiler command
   FFLAGS      Fortran 77 compiler flags
+  APXS
 
 Use these variables to override the choices made by `configure' or to help
 it to find libraries and programs with nonstandard names/locations.
@@ -6646,7 +6648,7 @@ ia64-*-hpux*)
   ;;
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 6649 "configure"' > conftest.$ac_ext
+  echo '#line 6651 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -9444,11 +9446,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:9447: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:9449: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:9451: \$? = $ac_status" >&5
+   echo "$as_me:9453: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -9734,11 +9736,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:9737: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:9739: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:9741: \$? = $ac_status" >&5
+   echo "$as_me:9743: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -9838,11 +9840,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:9841: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:9843: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:9845: \$? = $ac_status" >&5
+   echo "$as_me:9847: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -12200,7 +12202,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 12203 "configure"
+#line 12205 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -12300,7 +12302,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 12303 "configure"
+#line 12305 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -14720,11 +14722,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:14723: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:14725: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:14727: \$? = $ac_status" >&5
+   echo "$as_me:14729: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -14824,11 +14826,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:14827: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:14829: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:14831: \$? = $ac_status" >&5
+   echo "$as_me:14833: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -16399,11 +16401,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:16402: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:16404: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:16406: \$? = $ac_status" >&5
+   echo "$as_me:16408: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -16503,11 +16505,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:16506: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:16508: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:16510: \$? = $ac_status" >&5
+   echo "$as_me:16512: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -18703,11 +18705,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:18706: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:18708: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:18710: \$? = $ac_status" >&5
+   echo "$as_me:18712: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -18993,11 +18995,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:18996: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:18998: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:19000: \$? = $ac_status" >&5
+   echo "$as_me:19002: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -19097,11 +19099,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:19100: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:19102: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:19104: \$? = $ac_status" >&5
+   echo "$as_me:19106: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -22913,34 +22915,35 @@ fi
 # check apxs tool
 
 
-# check for --with-apxs
-{ echo "$as_me:$LINENO: checking for --with-apxs" >&5
+
+    if test -z "$APXS"
+  then
+    { echo "$as_me:$LINENO: checking for --with-apxs" >&5
 echo $ECHO_N "checking for --with-apxs... $ECHO_C" >&6; }
 
 # Check whether --with-apxs was given.
 if test "${with_apxs+set}" = set; then
-  withval=$with_apxs;
-  if test -x "$withval"
-  then
-    { echo "$as_me:$LINENO: result: $withval executable, good" >&5
-echo "${ECHO_T}$withval executable, good" >&6; }
-    APXS=$withval
-  else
-    echo
-    { { echo "$as_me:$LINENO: error: $withval not found or not executable" >&5
-echo "$as_me: error: $withval not found or not executable" >&2;}
-   { (exit 1); exit 1; }; }
-  fi
+  withval=$with_apxs;  if test "$withval" != "yes"
+                  then
+                    APXS="$withval"
+                    { echo "$as_me:$LINENO: result: $withval" >&5
+echo "${ECHO_T}$withval" >&6; }
+                  else
+                    { echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+                  fi
 
 else
-  { echo "$as_me:$LINENO: result: no" >&5
+   { echo "$as_me:$LINENO: result: no" >&5
 echo "${ECHO_T}no" >&6; }
+
 fi
 
+  fi
 
-# find apxs
-if test -z "$APXS"; then
-  for ac_prog in apxs2 apxs
+    if test -z "$APXS"
+  then
+    for ac_prog in apxs2 apxs
 do
   # Extract the first word of "$ac_prog", so it can be a program name with args.
 set dummy $ac_prog; ac_word=$2
@@ -22985,12 +22988,47 @@ fi
 
   test -n "$APXS" && break
 done
-test -n "$APXS" || APXS="false"
+test -n "$APXS" || APXS="no"
 
-  test "${APXS}" = "false" && { { echo "$as_me:$LINENO: error: failed to find apxs. Try using --with-apxs" >&5
-echo "$as_me: error: failed to find apxs. Try using --with-apxs" >&2;}
+  fi
+
+if test "$APXS" = "no"; then
+    { { echo "$as_me:$LINENO: error: apxs executable does not exist (use --with-apxs)" >&5
+echo "$as_me: error: apxs executable does not exist (use --with-apxs)" >&2;}
    { (exit 1); exit 1; }; }
 fi
+# check for ap_release.h
+# if present we have a apache 2.0.x and greater (in lower it's not included)
+# syntax of \#define AP_SERVER_MAJORVERSION differ in minor versions
+APXS_INCDIR="`${APXS} -q INCLUDEDIR`"
+as_ac_File=`echo "ac_cv_file_$APXS_INCDIR/ap_release.h" | $as_tr_sh`
+{ echo "$as_me:$LINENO: checking for $APXS_INCDIR/ap_release.h" >&5
+echo $ECHO_N "checking for $APXS_INCDIR/ap_release.h... $ECHO_C" >&6; }
+if { as_var=$as_ac_File; eval "test \"\${$as_var+set}\" = set"; }; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  test "$cross_compiling" = yes &&
+  { { echo "$as_me:$LINENO: error: cannot check for file existence when cross compiling" >&5
+echo "$as_me: error: cannot check for file existence when cross compiling" >&2;}
+   { (exit 1); exit 1; }; }
+if test -r "$APXS_INCDIR/ap_release.h"; then
+  eval "$as_ac_File=yes"
+else
+  eval "$as_ac_File=no"
+fi
+fi
+ac_res=`eval echo '${'$as_ac_File'}'`
+	       { echo "$as_me:$LINENO: result: $ac_res" >&5
+echo "${ECHO_T}$ac_res" >&6; }
+if test `eval echo '${'$as_ac_File'}'` = yes; then
+  { echo "$as_me:$LINENO: apache version >=2.0.x found" >&5
+echo "$as_me: apache version >=2.0.x found" >&6;}
+else
+  { { echo "$as_me:$LINENO: error: apache version >=2.0.x not found." >&5
+echo "$as_me: error: apache version >=2.0.x not found." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+
 
 # check apr-config
 
